package com.subha;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

public class Frameday3 {
	private void m1(int a) {

}
	private void m2(int a,int b) {
}
	private void m3 (ArrayList<String> s){
		
		}
	private void m4 (Map <String,String >m){
		// todo autogenerated method
}
	public static void main(String[] args) {
		Frameday3 a =new Frameday3();
		a.m1(100);
		a.m2(12,24);
	
	ArrayList<String> s = new ArrayList<>();
	s.add("ram");
	s.add("java");
	s.add("chennai");
	a.m3(s);
	Map<String,String > m = new LinkedHashMap<>();
	m.put("name","Bala");
	m.put("email","Bala@gmail.com");
	m.put("course","java");
			a.m4(m);
			System.out.println(a);
			System.out.println(s);
			System.out.println(m);

			
			
	
}
}